spring:
  profiles:
    active: dev
  application:
    name: Journal App
    data:
      mongodb:
        uri: ${MONGODB_URI:mongodb://localhost:27017}
        database: journaldb
        auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:YOUR_USERNAME_HERE}
    password: ${MAIL_PASSWORD:YOUR_PASSWORD_HERE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /our-journal

security:
  jwt:
    secret-key: ${SECRET_KEY_FOR_JWT_SIGNING}

api:
  weatherstack:
    key: ${WEATHERSTACK_API_KEY:YOUR_WEATHERSTACK_KEY_HERE}
  ninjas:
    key: ${NINJAS_API_KEY:YOUR_NINJAS_KEY_HERE}