spring:
  application:
    name: Journal App
  data:
    mongodb:
      uri: mongodb+srv://dhrubamaitra22_db_user:P0EdvxN1vcHSGDWo@cluster0.owca3om.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /our-journal